/**
 * Generated by scripts/clone-errors-data-for-client.mjs from
 * src/errors-data.ts. The client bundle needs its own module so bunchee
 * cannot put CMS_ERRORS in a shared use-client chunk.
 */

export const CMS_ERRORS = {
  BRANCH_NOT_FOUND: { status: 404 as const, message: 'Branch not found' },
  BLOCK_NOT_FOUND: {
    status: 404 as const,
    message: 'Block not found in snapshot',
  },
  PARENT_NOT_FOUND: { status: 404 as const, message: 'Parent block not found' },
  BLOCK_NOT_ALLOWED_IN_PARENT: {
    status: 400 as const,
    message: 'This block type is not allowed inside the target parent',
  },
  PROTECTED_BRANCH: {
    status: 403 as const,
    message:
      'Direct edits to a published branch are not allowed; work on a separate branch and merge, or unpublish first',
  },
  COMMIT_MESSAGE_REQUIRED: {
    status: 400 as const,
    message: 'A commit message is required for this operation',
  },
  ROOT_NOT_FOUND: {
    status: 404 as const,
    message: 'Root block not found in snapshot',
  },
  ROOT_HAS_CHILDREN: {
    status: 409 as const,
    message:
      'Cannot delete a root that has child roots; archive or move the children first',
  },
  ROOT_IN_USE: {
    status: 409 as const,
    message:
      'Cannot delete: this root is embedded as a reusable block on live roots; remove those references first',
  },
  COMMIT_NOT_FOUND: { status: 404 as const, message: 'Commit not found' },
  HEAD_MISMATCH: {
    status: 409 as const,
    message:
      'The branch has advanced since expectedHeadCommitId was read; reload and retry',
  },
  FOLDER_NOT_FOUND: { status: 404 as const, message: 'Folder not found' },
  FOLDER_HAS_CONTENT: {
    status: 409 as const,
    message: 'Cannot delete folder that contains assets or subfolders',
  },
  EMPTY_SNAPSHOT: {
    status: 400 as const,
    message: 'Empty snapshot — no versions found',
  },
  BLOCK_ALREADY_DELETED: {
    status: 400 as const,
    message: 'Block is already deleted',
  },
  TYPE_MISMATCH: {
    status: 400 as const,
    message: 'Block type does not match the expected type',
  },
  USER_ID_REQUIRED: {
    status: 400 as const,
    message:
      'userId is required for this route when neither the request nor middleware provides one',
  },
  CANNOT_MOVE_ROOT: {
    status: 400 as const,
    message: 'Cannot move the root block',
  },
  CANNOT_MOVE_INTO_SELF: {
    status: 400 as const,
    message: 'Cannot move an item into itself',
  },
  CANNOT_MOVE_INTO_DESCENDANT: {
    status: 400 as const,
    message: 'Cannot move an item into its own descendant',
  },
  MISSING_TARGET_PROPERTIES: {
    status: 400 as const,
    message: 'targetProperties is required when duplicating a root',
  },
  DUPLICATE_BLOCK_REQUIRES_PARENT: {
    status: 400 as const,
    message:
      'duplicateBlock requires targetParentBlockId; use duplicateRoot to duplicate a root',
  },
  BRANCH_NAME_ALREADY_EXISTS: {
    status: 409 as const,
    message: 'A branch with this name already exists for this root',
  },
  CANNOT_RENAME_MAIN_BRANCH: {
    status: 400 as const,
    message: 'The main branch cannot be renamed',
  },
  CANNOT_DELETE_MAIN_BRANCH: {
    status: 400 as const,
    message: 'The main branch cannot be deleted',
  },
  BRANCH_HAS_PUBLICATIONS: {
    status: 409 as const,
    message: 'Cannot delete a branch that has active publications',
  },
  BRANCH_HAS_OPEN_MERGE_REQUESTS: {
    status: 409 as const,
    message: 'Cannot delete a branch that is part of open merge requests',
  },
  NO_COMMON_ANCESTOR: {
    status: 400 as const,
    message: 'The two branches share no common ancestor',
  },
  MERGE_REQUEST_NOT_FOUND: {
    status: 404 as const,
    message: 'Merge request not found',
  },
  MERGE_REQUEST_NOT_OPEN: {
    status: 400 as const,
    message: 'Merge request is not open',
  },
  MERGE_REQUEST_NOT_CLOSED: {
    status: 400 as const,
    message: 'Merge request is not closed',
  },
  MERGE_REQUEST_ALREADY_MERGED: {
    status: 400 as const,
    message: 'Merge request has already been merged and cannot be reopened',
  },
  MERGE_REQUEST_ALREADY_EXISTS: {
    status: 409 as const,
    message:
      'An open merge request already exists for this source and target branch',
  },
  UNRESOLVED_CONFLICTS: {
    status: 400 as const,
    message: 'Cannot merge: there are unresolved conflicts',
  },
  CONFLICT_NOT_FOUND: {
    status: 404 as const,
    message: 'Merge conflict not found',
  },
  RESOLVED_VERSION_NOT_FOUND: {
    status: 404 as const,
    message:
      'The provided resolvedVersionId does not reference an existing block version',
  },
  APPROVAL_NOT_FOUND: {
    status: 404 as const,
    message: 'Approval not found',
  },
  APPROVAL_ALREADY_REQUESTED: {
    status: 400 as const,
    message: 'An approval has already been requested from this reviewer',
  },
  APPROVAL_NOT_PENDING: {
    status: 400 as const,
    message: 'Approval is not pending',
  },
  APPROVAL_REVIEWER_MISMATCH: {
    status: 403 as const,
    message: 'Only the requested reviewer can approve or reject this request',
  },
  APPROVAL_STALE: {
    status: 400 as const,
    message:
      'Approval is stale: the branch has advanced past the approved commit',
  },
  MERGE_APPROVAL_REQUIRED: {
    status: 400 as const,
    message: 'Cannot merge: approval is required before execution',
  },
  PUBLICATION_APPROVAL_REQUIRED: {
    status: 400 as const,
    message: 'Cannot publish: approval is required before publication',
  },
  APPROVALS_NOT_FULLY_APPROVED: {
    status: 400 as const,
    message: 'Cannot proceed: not all requested approvals are approved',
  },
  APPROVALS_STALE: {
    status: 409 as const,
    message:
      'The source branch has new commits since it was approved; request approval again',
  },
  BRANCHES_NOT_SAME_ROOT: {
    status: 400 as const,
    message: 'Source and target branches must belong to the same root',
  },
  PUBLICATION_NOT_FOUND: {
    status: 404 as const,
    message: 'Publication not found for this branch',
  },
  PUBLISHED_CONTENT_NOT_FOUND: {
    status: 404 as const,
    message: 'No published content found',
  },
  AMBIGUOUS_SLUG: {
    status: 400 as const,
    message:
      'Multiple roots match this slug — use rootId for an unambiguous lookup',
  },
  DATA_RETENTION_NOT_CONFIGURED: {
    status: 400 as const,
    message: 'dataRetention is not configured for this CMS instance',
  },
  MISSING_REQUIRED_S3_PARAMETERS: {
    status: 400 as const,
    message:
      'Missing required S3 parameters: hostname, accessKeyId, or secretAccessKey',
  },
  UNKNOWN_S3_PROVIDER: {
    status: 400 as const,
    message: 'Unknown S3 provider specified',
  },
  SLUG_GENERATION_FAILED: {
    status: 500 as const,
    message: 'Failed to generate a unique slug after maximum attempts',
  },
  TOO_MANY_FILES: {
    status: 400 as const,
    message: 'Too many files in upload batch',
  },
  FILE_TOO_LARGE: {
    status: 400 as const,
    message: 'One or more files exceed the maximum allowed size',
  },
  INVALID_FILE_TYPE: {
    status: 400 as const,
    message: 'One or more files have a disallowed MIME type',
  },
  UPLOAD_FAILED: {
    status: 500 as const,
    message: 'Server-side upload to S3 failed',
  },
  SLUG_ALREADY_EXISTS: {
    status: 409 as const,
    message:
      'A root with this slug on this collection with this parentRootId already exists',
  },
  PUBLISH_SLUG_CONFLICT: {
    status: 409 as const,
    message:
      'Cannot publish: another live root in this scope already uses this slug. Drafts may hold colliding slugs, but a published slug must be unique — change this slug (or unpublish the other root) before publishing.',
  },
  SLUG_NOT_ENABLED: {
    status: 400 as const,
    message: 'This collection does not have slugs enabled',
  },
  REDIRECT_NOT_FOUND: {
    status: 404 as const,
    message: 'Redirect not found',
  },
  REDIRECT_INVALID: {
    status: 400 as const,
    message:
      'A redirect endpoint must be a page (rootId) or a path, matching its type',
  },
  REDIRECT_SOURCE_EXISTS: {
    status: 409 as const,
    message: 'An active redirect already exists for this source',
  },
  SLUG_EMPTY_NOT_ALLOWED: {
    status: 400 as const,
    message:
      'Empty slug is not allowed for this collection (allowIndex is false)',
  },
  NESTING_NOT_ENABLED: {
    status: 400 as const,
    message:
      'parentRootId is not allowed — this collection does not have nested roots enabled',
  },
  CIRCULAR_REFERENCE: {
    status: 400 as const,
    message: 'Cannot move a root under itself or one of its descendants',
  },
  PARENT_ROOT_NOT_FOUND: {
    status: 404 as const,
    message: 'Parent root not found in this collection',
  },
  REFERENCE_DEPTH_EXCEEDED: {
    status: 422 as const,
    message:
      'Reference nesting is too deep (a reusable block embeds others past the limit)',
  },
  INVALID_REFERENCE: {
    status: 400 as const,
    message:
      'A property points at an image asset or reference id that does not exist',
  },
  ASSET_NOT_FOUND: { status: 404 as const, message: 'Asset not found' },
  CANNOT_REPLACE_VARIANT: {
    status: 400 as const,
    message:
      'Cannot replace a variant asset directly; replace the original and regenerate its variants',
  },
  VARIABLE_NOT_FOUND: { status: 404 as const, message: 'Variable not found' },
  VARIABLE_KEY_EXISTS: {
    status: 409 as const,
    message: 'A variable with this key already exists',
  },
  VARIABLE_IN_USE: {
    status: 409 as const,
    message: 'Cannot delete variable: it is still in use',
  },
  TEMPLATE_NOT_FOUND: { status: 404 as const, message: 'Template not found' },
  TEMPLATE_PROPERTY_INVALID: {
    status: 400 as const,
    message:
      'A template can only target an existing text property (type `string` or `richText`) of the block type',
  },
  TEMPLATE_KEY_EXISTS: {
    status: 409 as const,
    message:
      'A template for this collection/block/property combination already exists',
  },
  ASSET_ACCESS_DENIED: {
    status: 403 as const,
    message: 'This asset is private and requires authentication',
  },
  COMMENT_THREAD_NOT_FOUND: {
    status: 404 as const,
    message: 'Comment thread not found',
  },
  COMMENT_THREAD_ALREADY_RESOLVED: {
    status: 400 as const,
    message: 'Comment thread is already resolved',
  },
  COMMENT_THREAD_NOT_RESOLVED: {
    status: 400 as const,
    message: 'Comment thread is not resolved',
  },
  COMMENT_MESSAGE_NOT_FOUND: {
    status: 404 as const,
    message: 'Comment message not found',
  },
  COMMENT_MESSAGE_DELETED: {
    status: 400 as const,
    message: 'Comment message has been deleted',
  },
  COMMENT_AUTHOR_MISMATCH: {
    status: 403 as const,
    message: 'Only the author can edit or delete this message',
  },
  NOTIFICATION_NOT_FOUND: {
    status: 404 as const,
    message: 'Notification not found',
  },
  NOTIFICATION_RECIPIENT_MISMATCH: {
    status: 403 as const,
    message: 'You can only access your own notifications',
  },
} as const;

export type CMSErrorCode = keyof typeof CMS_ERRORS;
