import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { coreSchema } from '../core-schema';
import { emitDrizzleSchema } from '../emit';
import { mergeSchemaSources, type SchemaSource } from '../merge';

const here = path.dirname(fileURLToPath(import.meta.url));

/** Emit a hand-built source (merge first so the input is valid by construction). */
const emit = (source: SchemaSource) =>
  emitDrizzleSchema(mergeSchemaSources([source]));

const richSource: SchemaSource = {
  name: 'core',
  schema: {
    enums: { status: { values: ['active', 'inactive'] } },
    tables: {
      items: {
        columns: {
          id: {
            type: 'text',
            primaryKey: true,
            defaultId: true,
            defaultIdPrefix: 'item',
          },
          status: { type: { enum: 'status' }, notNull: true },
          count: { type: 'integer', default: { kind: 'literal', value: 0 } },
          createdAt: { type: 'timestamp', defaultNow: true },
          slug: { type: 'text', unique: true },
          meta: { type: 'jsonb', jsonType: 'Record<string, unknown>' },
          computed: { type: 'text', default: { kind: 'sql', value: 'now()' } },
        },
        indexes: {
          bySlug: { columns: ['slug'], unique: true },
          byMeta: { columns: ['meta'], using: 'gin' },
          activeOnly: { columns: ['status'], where: "status = 'active'" },
        },
      },
    },
  },
};

describe('emitDrizzleSchema — file shape', () => {
  it('emits the generated-file header + pgSchema + import block', () => {
    const out = emit(richSource);
    expect(out).toContain('/* eslint-disable */');
    expect(out).toContain('This file is generated by createcms.');
    expect(out).toContain("export const cmsSchema = pgSchema('cms');");
    expect(out).toContain("import { sql } from 'drizzle-orm';"); // sql default + where
    expect(out).toContain("from 'drizzle-orm/pg-core'");
    expect(out).toContain("import { newId } from '@createcms/core/nanoid';"); // defaultId
  });

  it('emits the enum + the schema-object export', () => {
    const out = emit(richSource);
    expect(out).toContain(
      'export const statusEnum = cmsSchema.enum("status", ["active", "inactive"]);',
    );
    expect(out).toContain('export const schema = {');
    expect(out).toMatch(
      /export const schema = \{[^}]*\bitems,[^}]*\bstatusEnum,/s,
    );
  });

  it('honors the nanoidImport option', () => {
    const out = emitDrizzleSchema(mergeSchemaSources([richSource]), {
      nanoidImport: "import { newId } from './local';",
    });
    expect(out).toContain("import { newId } from './local';");
    expect(out).not.toContain('@createcms/core/nanoid');
  });
});

describe('emitDrizzleSchema — column builders', () => {
  it('renders each column modifier', () => {
    const out = emit(richSource);
    expect(out).toContain(
      'id: text("id").primaryKey().$defaultFn(() => newId("item")),',
    );
    expect(out).toContain('status: statusEnum("status").notNull(),');
    expect(out).toContain('count: integer("count").default(0),');
    expect(out).toContain('createdAt: timestamp("created_at").defaultNow(),');
    expect(out).toContain('slug: text("slug").unique(),');
    expect(out).toContain(
      'meta: jsonb("meta").$type<Record<string, unknown>>(),',
    );
    expect(out).toContain(
      'computed: text("computed").default(sql.raw("now()")),',
    );
  });

  it('emits a cross-table reference and a SELF reference (AnyPgColumn)', () => {
    const out = emit({
      name: 'core',
      schema: {
        tables: {
          nodes: {
            columns: {
              id: { type: 'text', primaryKey: true },
              parentId: {
                type: 'text',
                references: {
                  table: 'nodes',
                  column: 'id',
                  onDelete: 'cascade',
                  onUpdate: 'restrict',
                },
              },
            },
          },
        },
      },
    });
    expect(out).toContain(
      'parentId: text("parent_id").references((): AnyPgColumn => nodes.id, { onDelete: "cascade", onUpdate: "restrict" }),',
    );
    expect(out).toContain(
      "import type { AnyPgColumn } from 'drizzle-orm/pg-core';",
    );
  });

  it('emits a tsvector custom column + its customType definition', () => {
    const out = emit({
      name: 'core',
      schema: {
        tables: {
          docs: {
            columns: { id: { type: 'text' }, search: { type: 'tsvector' } },
          },
        },
      },
    });
    expect(out).toContain('search: tsvectorColumn("search"),');
    expect(out).toContain(
      'const tsvectorColumn = customType<{ data: string }>(',
    );
    expect(out).toMatch(
      /import \{[^}]*\bcustomType\b[^}]*\} from 'drizzle-orm\/pg-core';/,
    );
  });

  it('throws when defaultId has no defaultIdPrefix', () => {
    const merged = mergeSchemaSources([
      {
        name: 'core',
        schema: {
          tables: { t: { columns: { id: { type: 'text', defaultId: true } } } },
        },
      },
    ]);
    expect(() => emitDrizzleSchema(merged)).toThrow(
      /defaultId but no defaultIdPrefix/,
    );
  });
});

describe('emitDrizzleSchema — indexes, composite PK, foreign keys', () => {
  it('emits plain / unique / gin / partial indexes', () => {
    const out = emit(richSource);
    expect(out).toContain('uniqueIndex("items_by_slug").on(table.slug)');
    expect(out).toContain('index("items_by_meta").using("gin", table.meta)');
    expect(out).toContain(
      'index("items_active_only").on(table.status).where(sql',
    );
  });

  it('emits a composite primary key + a table-level foreign key', () => {
    const out = emit({
      name: 'core',
      schema: {
        tables: {
          users: { columns: { id: { type: 'text', primaryKey: true } } },
          memberships: {
            columns: { userId: { type: 'text' }, orgId: { type: 'text' } },
            compositePrimaryKey: { columns: ['userId', 'orgId'] },
            foreignKeys: [
              {
                columns: ['userId'],
                foreignTable: 'users',
                foreignColumns: ['id'],
                onDelete: 'cascade',
                onUpdate: 'restrict',
              },
            ],
          },
        },
      },
    });
    expect(out).toContain(
      'primaryKey({ columns: [table.userId, table.orgId] }),',
    );
    expect(out).toContain('columns: [table.userId],');
    expect(out).toContain('foreignColumns: [users.id],');
    expect(out).toContain('.onDelete("cascade").onUpdate("restrict"),');
    // foreignKey + primaryKey must be in the pg-core IMPORT line (the bare names
    // also appear in the table body, so assert against the import specifically).
    expect(out).toMatch(
      /import \{[^}]*\bforeignKey\b[^}]*\} from 'drizzle-orm\/pg-core';/,
    );
    expect(out).toMatch(
      /import \{[^}]*\bprimaryKey\b[^}]*\} from 'drizzle-orm\/pg-core';/,
    );
  });
});

describe('emitDrizzleSchema — type aliases + determinism', () => {
  it('emits singularized PascalCase Select/Insert type aliases', () => {
    const out = emit({
      name: 'core',
      schema: {
        tables: {
          entries: { columns: { id: { type: 'text' } } },
          branches: { columns: { id: { type: 'text' } } },
        },
      },
    });
    expect(out).toContain('export type Entry = typeof entries.$inferSelect;');
    expect(out).toContain(
      'export type NewEntry = typeof entries.$inferInsert;',
    );
    expect(out).toContain('export type Branch = typeof branches.$inferSelect;');
  });

  it('orders enums + tables deterministically by key (sorted)', () => {
    const out = emit({
      name: 'core',
      schema: {
        enums: { zed: { values: ['z'] }, apple: { values: ['a'] } },
        tables: {
          zebra: { columns: { c: { type: { enum: 'apple' } } } },
          alpha: { columns: { c: { type: { enum: 'zed' } } } },
        },
      },
    });
    expect(out.indexOf('export const alpha')).toBeLessThan(
      out.indexOf('export const zebra'),
    );
    expect(out.indexOf('appleEnum')).toBeLessThan(out.indexOf('zedEnum'));
  });
});

describe('emitDrizzleSchema — coreSchema round-trip', () => {
  it('reproduces the committed schema.generated.ts (drift guard)', async () => {
    // Mirrors scripts/generate-schema.ts exactly. Fails if core-schema.ts or
    // emit changed without re-running `bun run generate:schema`.
    const merged = mergeSchemaSources([{ name: 'core', schema: coreSchema }]);
    const emitted = emitDrizzleSchema(merged, {
      nanoidImport: "import { newId } from '../../utils/nanoid';",
    });
    const code = emitted.replace(
      ' * This file is generated by createcms.',
      ' * GENERATED from core-schema.ts by scripts/generate-schema.ts.\n' +
        ' * Run `bun run generate:schema` to regenerate.',
    );
    const committed = await readFile(
      path.resolve(here, '../schema.generated.ts'),
      'utf8',
    );
    expect(code).toBe(committed);
  });
});
