/**
 * Generates the package's runtime Drizzle schema (`schema.generated.ts`) from
 * the single hand-maintained source of truth: `core-schema.ts`.
 *
 * Run with: `bun run generate:schema`
 *
 * The generated file is committed — regenerate it whenever `core-schema.ts`
 * changes. It is the same `emitDrizzleSchema` pipeline the CLI uses for the
 * consumer's schema, so the package's runtime tables and the consumer's
 * generated tables always agree by construction.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { coreSchema } from '../src/core/db/core-schema';
import { emitDrizzleSchema } from '../src/core/db/emit';
import { mergeSchemaSources } from '../src/core/db/merge';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../src/core/db/schema.generated.ts');

const merged = mergeSchemaSources([{ name: 'core', schema: coreSchema }]);

const emitted = emitDrizzleSchema(merged, {
  nanoidImport: "import { newId } from '../../utils/nanoid';",
});

// Clarify provenance: this is the package's own runtime schema, generated from
// core-schema.ts (not the consumer-facing `createcms` output).
const code = emitted.replace(
  ' * This file is generated by createcms.',
  ' * GENERATED from core-schema.ts by scripts/generate-schema.ts.\n' +
    ' * Run `bun run generate:schema` to regenerate.',
);

writeFileSync(OUT, code, 'utf8');
console.log(
  `Wrote ${path.relative(process.cwd(), OUT)} (${code.length} bytes).`,
);
